### ISSUE TITLE
ERROR: Variable 'dur' not defined.

### ISSUE THREAD

**Issue by moxiddr** [jamshark70/ddwChucklib-livecode#13]
When recompiling Class library after installing the libraries got this error

ERROR: Variable 'dur' not defined.
in file '/Users/alvaro/Library/Application Support/SuperCollider/downloaded-quarks/ddwChucklib-livecode/clLiveCode-ext.sc'
  line 9 char 7:

  		^(dur == that.dur)
         
  	}

**Comment by jamshark70** [comment]
Hi, thanks for checking!

Check the current version of the code here: https://github.com/jamshark70/ddwChucklib-livecode/blob/master/clLiveCode-ext.sc -- `^(dur == that.dur)` doesn't exist anywhere in it.

Quarks will sometimes tell you that it has updated successfully when in fact it failed. That must be the case here -- if you're seeing that `dur` comparison in the code, you definitely have an old version.

Try this:

1. In the terminal, `cd` to the location of ddwChucklib-livecode (will be `... something .../downloaded-quarks/ddwChucklib-livecode`).

2. `git pull`

3. Probably have to repeat that for all the `ddw*` directories.
