### ISSUE TITLE
Runtime errors because of missing quark dependencies

### ISSUE THREAD

**Issue by clfest** [jamshark70/ddwChucklib-livecode#3]
I am using supercollider 3.9.0-rc2 on Ubuntu from my clone of the git repository.
I have:

ddwChucklib                1
ddwChucklib-livecode       0.3
ddwCommon                  1
ddwGUIEnhancements         1
ddwLivecodeInstruments     0.1
ddwMixerChannel            1
ddwPatterns                1
ddwPrototype               1
ddwTemperament             1
ddwVoicer                  1

loaded.

Still when I try the following code it seems to error out:

input:

\loadAllCl.eval;

post:

ERROR: Class not defined.
  in interpreted text
  line 284 char 21:

  			~tabs = TabbedView(~parentView, ~parentView.bounds.insetBy(2, 2), ~tabSpecs[0, 2 ..])
                       
  			.backgrounds_([~model.tabBackground]);
-----------------------------------
WARNING: String:loadPath found nil, empty contents or parse error in  /home/clfest/.local/share/SuperCollider/downloaded-quarks/ddwChucklib-livecode/mobile-objects.scd
ERROR: Class not defined.
  in interpreted text
  line 38 char 16:

  			~eq = MultiEQ(2, \bhipass, 104.018, 0.dbamp, 0.369).play(chan);
                  
  		}
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 77 char 15:

  		~eq = MultiEQ(2, \bhipass, 105.84, 0.dbamp, 0.474).play(chan);
                 
  	});
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 120 char 15:

  		~eq = MultiEQ(2, \bhipass, 147.185, 0.dbamp, 0.504).play(chan);
                 
  	});
-----------------------------------
WARNING: String:loadPath found nil, empty contents or parse error in  /home/clfest/.local/share/SuperCollider/downloaded-quarks/ddwLivecodeInstruments/bass-vc.scd
ERROR: Class not defined.
  in interpreted text
  line 73 char 28:

  	realAmp = amp * Sensitivity.kr(1, gateLatch, vsens),
                              
  	exc = COsc.ar(bufnum, excFreq, beats, realAmp) * EnvGen.ar(Env.perc(0.01, excTime)),
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 82 char 26:

  	time = time * Sensitivity.kr(1, gateLatch, vTimeSens);
                            
  	sig = Mix(ratios.collect { |ratio, i|
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 200 char 46:

  	out.mapGlobal(\ratio, nil, 2, SnapControlSpec(1, 10, \lin, 1).snap_(0.15));
                                                
  	out.mapGlobal(\modAmt, nil, 1.5, [0, 3]);
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 232 char 9:

  		MultiEQ.new(2, \eq, 279.743, -3.759.dbamp, 1, \eq, 10341.84, 3.759.dbamp, 1).play(chan);
           
  		~chorus = chan.playfx(Instr("busfx.chorus2"), [0, 2, 2, 3, 0.013676047024487, 0.24669302064117, 0.0076241645277023, 2.0019953184641, 0.7290294928589]);
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 351 char 17:

  				~eq = MultiEQ.new(2,
                   
  					\hipass, 132.629, 0.dbamp, 1,
-----------------------------------
WARNING: String:loadPath found nil, empty contents or parse error in  /home/clfest/.local/share/SuperCollider/downloaded-quarks/ddwLivecodeInstruments/chord-vc.scd
ERROR: Class not defined.
  in interpreted text
  line 27 char 16:

  			~eq = MultiEQ(2,
                  
  				\bhipass, 67.401, 0.dbamp, 0.534,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 51 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\eq, 132.629, -9.474.dbamp, 0.085,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 70 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\eq, 123.733, -8.271.dbamp, 0.16,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 91 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\eq, 201.16, -11.278.dbamp, 0.055,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 108 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\eq, 2324.645, -11.579.dbamp, 0.07
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 124 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\hipass, 247.739, 0.dbamp, 1,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 145 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\hipass, 239.287, 0.dbamp, 1
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 160 char 16:

  			~eq = MultiEQ.new(2,
                  
  				\eq, 183.174, -8.271.dbamp, 0.24,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 385 char 16:

  			~eq = MultiEQ(2,
                  
  				\eq, 9001.115, 3.dbamp, 1,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 405 char 16:

  			~eq = MultiEQ(2,
                  
  				\eq, 3232.754, -3.459.dbamp, 0.055,
-----------------------------------
WARNING: String:loadPath found nil, empty contents or parse error in  /home/clfest/.local/share/SuperCollider/downloaded-quarks/ddwLivecodeInstruments/drum-samples.scd
ERROR: Class not defined.
  in interpreted text
  line 78 char 16:

  		~eq = StaticEQ.new(2, \hipass, 201.16, 0.dbamp, 1, \hipass, 201.16, 0.dbamp, 1).play(chan);
                  
  	});
-----------------------------------
WARNING: String:loadPath found nil, empty contents or parse error in  /home/clfest/.local/share/SuperCollider/downloaded-quarks/ddwLivecodeInstruments/lead-vc.scd
ERROR: Class not defined.
  in interpreted text
  line 614 char 15:

  	MIDIBufManager(TempoClock.default, nil) => MBM.prNew(0);
                 
  };
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 616 char 10:

  MIDIRecBuf(\bigch, [
            
  	[60, 64, 67, 69, 74, 77, 79,
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 625 char 10:

  MIDIRecBuf(\smallch, [
            
  	[60, 64, 67,  60, 65, 67,  60, 64, 69,  60, 62, 69,  60, 64, 71,  60, 62, 71,  60, 65, 71],
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 630 char 10:

  MIDIRecBuf(\one, [
            
  	[60],
-----------------------------------
ERROR: Class not defined.
  in interpreted text
  line 635 char 10:

  MIDIRecBuf(\two, [
            
  	[[48, 50, 52, 53, 55, 57, 59], 60].lace(14),
-----------------------------------
WARNING: String:loadPath found nil, empty contents or parse error in  /home/clfest/.local/share/SuperCollider/downloaded-quarks/ddwLivecodeInstruments/pitch-processes.scd
-> [ loadCl, loadClExtras, loadClInstr ]

input:
														
TempoClock.tempo = 124/60;
														
post:
														
-> TempoClock

input:
														
/hh.(\hardhh);
														
post:
														
ERROR: clPassThru: Func('hh') does not exist.

PROTECTED CALL STACK:
	a FunctionDef	0x51e07a8
		sourceCode = "{ |code|
		var i, ids, test;
		~parenIndex = code.indexOf(~endIDChar);
		// everything before ~parenIndex should be the ID string
		ids = code[.. ~parenIndex - 1].split($.).collect { |str| Func(\\strTrim).eval(str) };
		ids = Pseq(ids).asStream;

		// class (I expect this won't be used often)
		test = ids.next;
		if(test.first.isUpper) {
			~clClass = test.asSymbol.asClass;
			test = ids.next;
		};

		// chucklib object key
		~objKey = test.asSymbol;  // really? what about array types?
		if(...etc..."
		arg code = hh.(\hardhh)
		var i = nil
		var ids = a Routine
		var test = hh
	a FunctionDef	0x6b54d38
		sourceCode = "{ |code|
		~parseIDs.(code);
		~getCode.(code);
		\"%.eval(%)\".format(~objKey.asCompileString, ~codeToPass);
	}"
		arg code = hh.(\hardhh)
	a FunctionDef	0x2c4fdc0
		sourceCode = "<an open Function>"
	a FunctionDef	0x2c4de00
		sourceCode = "<an open Function>"
	Function:prTry	0x2281dc0
		arg this = a Function
		var result = nil
		var thread = a Thread
		var next = a Function
		var wasInProtectedFunc = true
	Function:protect	0x2281340
		arg this = a Function
		arg handler = a Function
		var result = nil
	Proto:use	0x2c4d880
		arg this = a Proto
		arg func = a Function
		arg failSilentlyAfterFree = false
		var result = nil
		var saveEnvir = a Proto
	Proto:doesNotUnderstand	0x2c4f680
		arg this = a Proto
		arg selector = process
		arg args = nil
		var result = [ hh.(\hardhh) ]
		var item = nil
	a FunctionDef	0x4c957b8
		sourceCode = "<an open Function>"
		arg assn = (clFuncCall -> ^ *`id\.\(.*\))
	ArrayedCollection:do	0x2ff6f00
		arg this = [ (clMake -> ^ *make\(.*\)), (clFuncCall -> ^ *`id\.\(.*\)), (clPassThru -> ^ *([A-Z][A-Za-z0-9_]*\.)?`id\(.*\)), (clChuck -> ^ *([A-Z][A-Za-z0-9_]*\.)?`id *=>.*), (clPatternSet -> ^ *`id(\.|`id|`id\*[0-9]+)* = .*), (clGenerator -> ^ *`id(\.|`id)* \*.*), (clXferPattern -> ^ *`id(\.`id)?(\*`int)? ->>), (clCopyPattern -> ^ *`id(\.`id)?(\*`int)? ->), (clStartStop -> ^([/`spc]*`id)+[`spc]*[+-]), (clPatternToDoc -> ^ *`id(\.|`id)*(\*[0-9]+)?[`spc]*$) ]
		arg function = a Function
		var i = 1
	a FunctionDef	0x3c16c08
		sourceCode = "<an open Function>"
		arg break = a Function
	a FunctionDef	0x2c4fdc0
		sourceCode = "<an open Function>"
	a FunctionDef	0x2c4de00
		sourceCode = "<an open Function>"
	Function:prTry	0x2281dc0
		arg this = a Function
		var result = nil
		var thread = a Thread
		var next = nil
		var wasInProtectedFunc = false
	
CALL STACK:
	Exception:reportError
		arg this = <instance of Error>
	Nil:handleError
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw
		arg this = <instance of Error>
	Function:protect
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of Error>
	Proto:use
		arg this = <instance of Proto>
		arg func = <instance of Function>
		arg failSilentlyAfterFree = false
		var result = nil
		var saveEnvir = <instance of Environment>
	Proto:doesNotUnderstand
		arg this = <instance of Proto>
		arg selector = 'process'
		arg args = [*1]
		var result = nil
		var item = <instance of Function>
	< FunctionDef in closed FunctionDef >
		arg stmt = "/hh.(\hardhh)"
		arg i = 0
	ArrayedCollection:do
		arg this = [*2]
		arg function = <instance of Function>
		var i = 0
	< closed FunctionDef >
		arg code = [*2]
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = nil
		var code = "/hh.(\hardhh);"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: clPassThru: Func('hh') does not exist.

So what's the hang?

**Comment by jamshark70** [comment]
Thanks for the report. I missed some dependencies -- I will fix it in about 12 hours, unfortunately I am judging auditions all day and I have no access to my computer until then.

In the meantime, install these and it should get you further... though I noticed one other reference (to an effect patch) that I can't fix right now.

- ddwEQ
- ddwMIDI
- ddwSensitivity
- TabbedView

Thanks for checking! These are easy to fix -- it's only that I'm trapped with work duties and I can't do anything about it for half a day...

**Comment by jamshark70** [comment]
This should be fixed now. You'll need to update three quarks:

```
["ddwCommon", "ddwChucklib-livecode", "ddwLivecodeInstruments"].do { |name|
	Quarks.update(name);
};
```

... and maybe reinstall "ddwChucklib-livecode" and "ddwLivecodeInstruments" to get all the dependencies.

Let me know how it goes --
