### ISSUE TITLE
error with cl-manual, chords, anapadVC

### ISSUE THREAD

**Issue by clfest** [jamshark70/ddwChucklib-livecode#6]
I seem to have waited a bit too long, and thus the other thread was closed. I'm running 3.9.0 compiled from git on Ubuntu Studio. I have updated, and I've updated the various ddw quarks too. It seems to pass your tests for newness, given on the other thread. Still it errors out at:

/make(anapadVC:pad/chordBP:ch(chords:\one));

but the error is different, it reads:

ERROR: syntax error, unexpected BINOP, expecting $end
in interpreted text
line 4 char 1:

?
^
ERROR: Command line parse failed
-> nil

/

**Comment by jamshark70** [comment]
If an issue is closed, there should be a button to "Reopen issue"... it's better to keep all the discussion in one place.

Thanks for the further info but let's continue under #4.
