### ISSUE TITLE
generators won't accept as quants 1/3, 1/7...

### ISSUE THREAD

**Issue by clfest** [jamshark70/ddwChucklib-livecode#7]
How would you make, let's say an \ins generator with a quant of for example 1/3? For example:
\ins(" - -", ".", 2, 1/3) doesn't work. It seems quant only accepts literal numbers with at most 3 decimal
places, and 0.333 is not exactly 1/3...?

**Comment by jamshark70** [comment]
I could add fractions like 1/3 -- that's a good feature request, thanks. I don't think I can support arbitrary math expressions like `a * 7 - 2`, but fractions would be easy.

I'm traveling now, so it'll be later.

I just tried this, and it worked, so there's no three-digit limitation.

```
\loadCl.eval;

(
PR(\abstractLiveCode).chuck(BP(\x), nil, (
	defaultParm: \x,
	parmMap: (x: ($-: 1, $.: 0)),
));
)

// this is OK
/x = "\ins("", ".", 3, 0.33333333333)";
```

**Comment by clfest** [comment]
Funny, when I execute this sequence:

\loadAllCl.eval
TempoClock.tempo = 124/60;
/drum.(\tightsnr);
/tsn = "\ins(" - -", ".", 2, 0.333)";
// no error
/tsn = "\ins(" - -", ".", 2, 0.3333)";
//error

ERROR: Message 'at' not understood.
RECEIVER:
   nil
ARGS:
   Symbol 'initialRest'
PATH: /home/clfest/clfest/SuperCollider/cl-manual_examples.scd

PROTECTED CALL STACK:
	Meta_MethodError:new	0x23f7280
		arg this = DoesNotUnderstandError
		arg what = nil
		arg receiver = nil
	Meta_DoesNotUnderstandError:new	0x23f9240
		arg this = DoesNotUnderstandError
		arg receiver = nil
		arg selector = at
		arg args = [ initialRest ]
	Object:doesNotUnderstand	0x1cb6440
		arg this = nil
		arg selector = at
		arg args = nil
	a FunctionDef	0x7462fe8
		sourceCode = "{ |items, quant, tolerance = 0.001|
			var i = 0, j = 0, time, avail = List.new,
			times = items.collect({ |item| item[\\time] - ~time }) ++ [~dur];
			time = i * quant;
			while {
				time < ~dur
			} {
				if(time absdif: times[j] < tolerance) {
					if(items[j][\\initialRest] == true) { avail.add(time) };
					// 'time' is matched at times[j], so we must advance by at least 1
					j = j + 1;
				} {
					avail.add(time);
					// times[j] is somewhere in the future; may not need to advanc...etc..."
		arg items = [ ( 'wildcard': -, 'time': 1, 'item': -, 'dur': 2 ), ( 'wildcard': -, 'time': 3, 'item': -, 'dur': 1 ) ]
		arg quant = 0.3333
		arg tolerance = 0.001
		var i = 12
		var j = 2
		var time = 3.9996
		var avail = List[ 0, 0.3333, 0.6666, 1.3332, 1.6665, 1.9998, 2.3331, 2.6664, 3.333, 3.6663 ]
		var times = [ 1, 3, 4 ]
	a FunctionDef	0x745efa8
		sourceCode = "{
			var avail = ~getAvail.(~items, ~quant).scramble;
			min(~numToAdd, avail.size).do { |i|
				var newTime = avail[i],
				new;
				// should be guaranteed but, protect against mistakes
				if(newTime.notNil) {
					new = ~poolStream.next;
					if(new.notNil) {
						~insertItem.((item: new, wildcard: new, src: \\ins, time: newTime));
					};
				};
			};
			~items
		}"
		var avail = nil
	a FunctionDef	0x7365ed8
		sourceCode = "{
			if(~doReset or: { ~seqStream.isNil }) {
				~makeStream.();
			};
			~items = ~getUpstreamItems.();
			~modifySource.();
			~items
		}"
	a FunctionDef	0x30aaf00
		sourceCode = "<an open Function>"
	a FunctionDef	0x30af8c0
		sourceCode = "<an open Function>"
	Function:prTry	0x26ba840
		arg this = a Function
		var result = nil
		var thread = a Routine
		var next = a Function
		var wasInProtectedFunc = true
	Function:protect	0x26b9dc0
		arg this = a Function
		arg handler = a Function
		var result = nil
	Proto:use	0x30af340
		arg this = a Proto
		arg func = a Function
		arg failSilentlyAfterFree = false
		var result = nil
		var saveEnvir = a Proto
	Proto:value	0x30aaa80
		arg this = a Proto
		arg args = nil
		var result = [  ]
	a FunctionDef	0x3358a00
		sourceCode = "<an open Function>"
		arg elem = a Proto
		arg i = 0
	ArrayedCollection:do	0x339cb80
		arg this = [ a Proto ]
		arg function = a Function
		var i = 0
	Collection:collectAs	0x3358640
		arg this = [ a Proto ]
		arg function = a Function
		arg class = Array
		var res = [  ]
	a FunctionDef	0x7355e58
		sourceCode = "{ |key(\\baseItems)|
			var out;
			// \">> % getUpstreamItems\".format(~protoID).debug;
			out = key.envirGet.asArray
			.collect { |item| item.value }
			.flatten(1)
			.collect { |item|
				if(item[\\wildcard].isNil) { item[\\wildcard] = item[\\item] };
				item
			};
			// \"<< % getUpstreamItems\".format(~protoID).debug;
			// out.postcs
		}"
		arg key = baseItems
		var out = nil
	a FunctionDef	0x7355a48
		sourceCode = "{
			~items = ~getUpstreamItems.();
		}"
	a FunctionDef	0x732c728
		sourceCode = "{
			var temp;
			if(~repository.isNil) {
				if(BP.exists(~bpKey)) {
					if(BP(~bpKey)[\\genRepository].notNil) {
						~repository = BP(~bpKey)[\\genRepository];
					} {
						~repository = IdentityDictionary.new;
						BP(~bpKey)[\\genRepository] = ~repository;
					};
				};
				if(~repository[~parm].isNil and: {
					temp = BP(~bpKey).parmMap[~parm].tryPerform(\\at, \\default);
					temp.notNil
				}) {
					~repository[~parm] = (time: 0, item: temp);
				};
			};
			~process.();
			i...etc..."
		var temp = nil
	a FunctionDef	0x7357448
		sourceCode = "{ |bp|  // the BP() object -- asPattern should be called @ top level only
			var pat, rest, didProcess = false;
			if(~items.isNil) {
				~items = ~doProcess.(bp);
				~updateDeltas.();
				// \"clGen items: \".post; ~items.postcs;
				didProcess = true;
			};
			// if(~items[0].time > 0) {
			// 	rest = [(time: 0, dur: ~items[0].time, item: Rest(~items[0].item))];
			// };
			// \"rest ++\" also works if 'rest' is nil
			pat = Pseq(rest ++ ~items, 1);
			if(BP.exists(~bpKey) and: { ~parm !=...etc..."
		arg bp = BP('tsn')
		var pat = nil
		var rest = nil
		var didProcess = false
	a FunctionDef	0x735a048
		sourceCode = "{ |inval|
			var dur = ~dur.(),
			startTime = thisThread.clock.beats,
			next, pitch, bp, rout;
			if(BP.exists(~bpKey)) {  // this also avoids 'nil'
				bp = BP(~bpKey);
			};

			~asPattern.(bp).embedInStream(inval);
		}"
		arg inval = ( 'clock': a TempoClock, 'eventKey': singleSynthPlayer, 'collIndex': tsn, 'timingOffset': 0, 
  'propagateDownward': a Function )
		var dur = 4
		var startTime = 504
		var next = nil
		var pitch = nil
		var bp = BP('tsn')
		var rout = nil
	a FunctionDef	0x30adcc0
		sourceCode = "<an open Function>"
	a FunctionDef	0x30af8c0
		sourceCode = "<an open Function>"
	Function:prTry	0x26ba840
		arg this = a Function
		var result = nil
		var thread = a Routine
		var next = nil
		var wasInProtectedFunc = true
	
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Function:protect
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of DoesNotUnderstandError>
	Proto:use
		arg this = <instance of Proto>
		arg func = <instance of Function>
		arg failSilentlyAfterFree = false
		var result = nil
		var saveEnvir = <instance of Proto>
	PatternProxy:embedInStream
		arg this = <instance of PatternProxy>
		arg inval = <instance of Event>
		arg embed = false
		arg default = nil
		var outval = nil
		var count = 0
		var pat = <instance of Pcollect>
		var test = true
		var resetTest = nil
		var stream = <instance of FuncStream>
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = <instance of Event>
^^ The preceding error dump is for ERROR: Message 'at' not understood.
RECEIVER: nil

**Comment by jamshark70** [comment]
Fixed: https://github.com/jamshark70/ddwChucklib-livecode/commit/40ea3ccf692ea8213895fcbca2e0a9d8a73b07b8

```
/make(pbsVC:pbs/melBP:bs(octave:3));

/bs = "\ins("1>1>1>1>", "1.", 12, 1/3)";
```

... is now OK.

I'll look into the `\ins` error above. Interesting one.
